### PR TITLE
Downloads Page

### PR DESCRIPTION
**Pull request by fortunee**
### Screenshot

2021-02-11 3 02 28 AM

### CODE REVIEW

**Review by AkinAguda — CHANGES_REQUESTED** [review]
Well done man. Looks really good. Only thing is, it's not really responsive. Images, fonts and all that. Other than that, things look pretty nice

**Comment by fortunee** [comment]
> Well done man. Looks really good. Only thing is, it's not really responsive. Images, fonts, and all that. Other than that, things look pretty nice

Thanks, dude! There's no mockup design for responsive view and I didn't want to layout the images off the top of my head!
@AkinAguda

**Comment by AkinAguda** [comment]
> > Well done man. Looks really good. Only thing is, it's not really responsive. Images, fonts, and all that. Other than that, things look pretty nice
> 
> Thanks, dude! There's no mockup design for responsive view and I didn't want to layout the images off the top of my head!
> @AkinAguda 

Oh cool. For now, you can make it responsive and it could look however you see fit. You can hide some illustrations you think are unnecessary on mobile

**Comment by mrbusysky** [comment]
Yeah once the mobile view is complete ill merge.

**Review by mrbusysky — CHANGES_REQUESTED** [review]
I agree with akin.

**Comment by fortunee** [comment]
Ok, it's fixed now! Please take another look.

cc: @AkinAguda @mrbusysky

**Pull request merged**
